### ISSUE TITLE
应该怎么对视频文件进行3d卷积训练

### ISSUE THREAD

**Issue by lishanlu136** [ZhaofanQiu/caffe-windows-3dConvNet#1]
嗨，你好，看你的名字好像是中国人，那我就用中文了，英文有些烂，按照你提供的资料，我生成了一个caffe.exe，因为你提供的example里面就只有三个微调的配置文件，所以还是不知道怎么训练，视频的训练和图片是一样的吗？对视频的标注是只标注一个还是对视频的每一帧都标注？看example里面的配置文件，好像你没有把视频转为leveldb或者lmdb，怎么直接输入了一个txt文件？tools文件夹里面的compute_image_mean.cpp，convert_imageset.cpp，extract_features.cpp等等，这些文件对视频都可以处理吗？我想把特征可视化该怎么办，是不是应该向处理图片一样，还得在工程里面配置Python？抱歉，提的问题有点多。

**Comment by ZhaofanQiu** [comment]
hi，你好，谢谢你的关注。因为这个repository我主要是用来备份代码，所以code的质量可能达不到public的级别，但如果你需要参考的话也是很欢迎的。
关于你的问题，正如我在readme里写的，这个code主要是基于C3D( https://github.com/facebook/C3D )，再做出了一些小改动，如果你需要用这套代码做3d卷积的训练的话，建议你参考一下C3D/examples/c3d_finetuning/里面的例子，是在ucf101数据集上训练的例子。
关于具体的问题：
1、视频和图片的训练主要是数据输入上的差别，还有就是图片在caffe里是4D的数据，而这套code里视频数据是5D的；
2、对视频是每个video一个label，但是训练的时候是一个clip一个label，例如在c3d里面是16帧一个clip，然后一个clip会有一个label，通常就是相应video的label；
3、txt的格式是因为针对video_data_layer.cpp这个数据层的格式，这个数据层是根据list文件直接访问原图片的，和image_data_layer.cpp直接读图片数据类似，并不是所有数据都要leveldb或lmdb输入。video_data层所用的数据格式是每行一个clip，具体可以参考c3d里面的例子；
4、tools里面那些cpp名字带image的肯定是不能处理视频数据的，extract_features应该是可以用的，但是没有测试过；
5、我没有尝试过在这套code上做数据可视化，另外这个code我也没有加入python或matlab编译过，如果要做可视化，可能抽出feature来再用别的code做可视化会容易一点。

**Comment by lishanlu136** [comment]
首先，感谢你这么详细的回复，按照你的说法，tools里面带image的都不能处理视频，那视频的均值怎么计算？你给的这个参考，我之前看过，是基于Ubuntu的；C3D/examples/c3d_finetuning/里面的例子是把视频的每一帧都保存为图片的（不过里面也说过可以直接输入视频），它是利用compute_volume_mean_from_list.cpp计算均值的，我看你做的微调，是利用compute_image_from_list.cpp计算均值的，你是直接按视频输入的吧。
还有就是你只是利用C3D模型做的微调吗？我要怎么训练自己的网络？我利用train_net.cpp生成一个Train_Net.exe，然后调用这个exe，后面跟了一个solver.prototxt，但是训练总是出错，是readImageSequenceToVolumeDatum（）这个函数出错，我是直接按视频读入的（没有像C3D里example那样把视频的每帧按图片保存下来），制作的txt格式为：视频地址，一个clip的起始帧，label。计算均值是用的是compute_image_from_list.cpp生成的exe，调用的格式为：前面制作的txt，new_height，new_width，输出文件。你能给我说说你制作的txt格式和怎么生成均值文件的吗？

**Comment by lulu2017** [comment]
@lishanlu136 你好，我最近也在用Windows下的3D caffe。请问你的问题解决了吗？我也想知道您是怎样生成均值文件和训练的。

**Comment by yzldw333** [comment]
你好，想和你请教一个问题，我在用tf的3dconv搭建了一个3dconvnet，复现手势识别那篇论文的结果，我的程序最终可以跑通，也验证过输入的数据是没有问题的，我做了白化， 为什么我的loss下不来，总是在2.8-3.0波动。由于没有机器，我最好的设备gtx960 只能带动20batchsize，但我用tensorboard看loss没有降下来， 请问你训练过程遇到这种问题么， 有的话可以给我一些提示么，我动了各种变量，但基本是复现论文的操作，从初始化到学习速率。

**Comment by songgup** [comment]
你好，一段视频可以跟着多label吗？
